<a href="https://colab.research.google.com/github/harshu4387/Student-Performance/blob/main/Student_Performance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Function
def func(name):
    print("Hello", name)

func("harshu")

def add(a, b):
    return a + b

result = add(5, 3)
print(result)



Hello harshu
8


In [ ]:
# callback function
def callback():
    print("callback function")

def mainfunction(callback):
    print("main function started")
    callback()
    print("main function ended")

# function call
mainfunction(callback)


main function started
callback function
main function ended


In [ ]:
# map with lambda
numbers = [1, 2, 3, 4]
result = list(map(lambda x: x * x, numbers))
print(result)


[1, 4, 9, 16]


In [ ]:
# filter method

number = [1,2,3,4,5,6]

evens = []
for n in numbers :
  if n % 2 ==0:
    evens.append(n)
print(evens)

    # method with filter
def even(x):
  return x % 2 ==0

number = [1,2,3,4,5,6]
result = list(filter(lambda x: x % 2 == 0, numbers))
print(result)

      # filter with lambda
number = [1,2,3,4,5,6]
result = list(filter(lambda x: x % 2== 0, numbers))
print(result)

[2, 4]
[2, 4]
[2, 4]


In [ ]:
# without reduce (using loop)
numbers = [1, 2, 3, 4]

total = 0
for n in numbers:
    total += n

print(total)


# with reduce (using function)
from functools import reduce

def add(a, b):
    return a + b

numbers = [1, 2, 3, 4]
result = reduce(add, numbers)

print(result)


# with reduce + lambda
numbers = [1, 2, 3, 4]
result = reduce(lambda a, b: a + b, numbers)

print(result)


10
10
10


In [ ]:
# numpy and basics
import numpy as np

# python list
lst = [1, 2, 3]
print(lst * 2)     # repeats the list

# numpy array
arr = np.array(lst)
print(arr * 2)     # multiplies each element


[1, 2, 3, 1, 2, 3]
[2 4 6]


In [ ]:
import numpy as np

# 1D array
arr = np.array([1, 2, 3, 4])
print(arr)

# 2D array (matrix) – fixed to be rectangular
matrix = np.array([[1, 2, 3, 4],
                   [4, 5, 6, 7]])
print(matrix)

# array properties (basic manipulation)
print(arr.ndim)    # number of dimensions
print(arr.shape)   # shape
print(arr.dtype)   # data type
print(arr.size)    # total number of elements

print(matrix.ndim)
print(matrix.shape)
print(matrix.size)
print(matrix.dtype)



[1 2 3 4]
[[1 2 3 4]
 [4 5 6 7]]
1
(4,)
int64
4
2
(2, 4)
8
int64


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

reshaped = arr.reshape(2, 3)
print(reshaped)

flat = reshaped.flatten()
print(flat)


[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [ ]:
def func(b, c):
    print(b + c)

a = 23
b = 23
func(a, b)


46


In [ ]:
matrix = np.array([[1,2,3,],
                  [4,5,6]])
print(matrix[0,1])
print(matrix[1,2])

2
6


In [ ]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])
print(arr[:3])
print(arr[::2])

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(matrix[:3, :2])
print(matrix[1:, 1:])
print(matrix[::2, ::2])


[20 30 40]
[10 20 30]
[10 30 50]
[[1 2]
 [4 5]
 [7 8]]
[[5 6]
 [8 9]]
[[1 3]
 [7 9]]


In [ ]:
import numpy as np

# 1D arrays
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)

# 2D arrays
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])

print(a + b)


[5 7 9]
[ 4 10 18]
[[ 6  8]
 [10 12]]
